CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ts DATETIME,
  tenant VARCHAR(50),
  event_type VARCHAR(50),
  src_ip VARCHAR(50),
  dst_ip VARCHAR(50),
  user VARCHAR(50),
  severity VARCHAR(20),
  msg TEXT,
  raw TEXT
);

CREATE TABLE IF NOT EXISTS alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rule_name VARCHAR(100),
  payload TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE,
  password VARCHAR(255),
  role VARCHAR(20),
  tenant VARCHAR(50)
);



